import React from 'react'
import { Button, styled} from "@mui/material";
import logo1 from "../assets/icons/home.png"
import logo2 from "../assets/icons/location.png"
import logo3 from "../assets/icons/documents.png"
import logo4 from "../assets/icons/badge.png"


import "../styles/section2.css";


function Logo(props) {
    return (
      <div className="logo-img">
        <img src={props.image} alt={props.alt} />
      </div>
    );
  };

const Card=(props) => {

    const {heading, para, image, alt} = props;
    return (
        <div className="card">
            <div className='card-content'>
            <div className='card-logo' >
            <Logo image={image} alt={alt}/>
            </div>
            <div className='card-text'>
            <h2>{heading}</h2>
            <p>{para}</p>
            </div>
            </div>
        </div>
    )
}


const Section2 = () => {

    const ApplyBtn = styled(Button)({
        backgroundColor: '#0193DC',
        padding:'11px 71px',
        fontSize: 18,
        fontFamily: 'Open sans',
        fontWeight:600,
        textTransform: 'none',
        letterSpacing: 0.7
    })


  return (
    <>
    <div className='container2'>
        <div className='content2'>
            <div className='content-items2'>
                <div className='column1 text-container2'>
                    <h2>
                    Our Vision
                    </h2>
                    <div className='text'>
                    <p>
                    To create a Startup Support System that enables 5% of
                    our students to follow an entrepreneurial career and
                    join the ranks of job creators, thereby contributing to
                    the social and economic development of India.
                    </p>
                    </div>

                    <ApplyBtn
                    variant='contained'
                    >
                        Apply Now
                    </ApplyBtn>
                </div>


                <div className='column2 components.container'>
                    <div className='coumn2-row1'>
                        <div className='card1'>
                            <Card image={logo1} alt="img" heading="Leaders in Idea Innovation" para="Lorem ipsum dolor sit amet adipcing aqua lorem ipsum"/>
                        </div>
                        <div className='card2'>
                            <Card image={logo2} alt="img" heading="Leaders in Project Incubation" para="Lorem ipsum dolor sit amet adipcing aqua lorem ipsum"/>
                        </div>
                    </div>
                    <div className='coumn2-row2'>
                    <div className='card1'>
                            <Card image={logo3} alt="img" heading="Leaders in Industry Corporation" para="Lorem ipsum dolor sit amet adipcing aqua lorem ipsumo"/>
                        </div>
                        <div className='card2'>
                            <Card image={logo4} alt="img" heading="30Cr+ Revenue generated by Startups" para="Lorem ipsum dolor sit amet adipcing aqua lorem ipsum"/>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
    </>
  )
}

export default Section2